[package]
name = "tksync"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde_yaml = "0.9"
serde = {version = "1.0", features = ['derive']}
clap = { version = "4.0", features = ['cargo']}