[package]
name = "tksync"
version = "0.1.1"
edition = "2021"

[dependencies]
confy = "0.5"
regex = "1.0"
anyhow = "1.0"
derive_more = "0.99"
clap = { version = "4.0", features = ['cargo']}
serde = {version = "1.0", features = ['derive']}
reqwest = { version = "0.11", features = ["blocking"]}
