[package]
name = "tksync"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.0"
anyhow = "1.0"
serde_yaml = "0.9"
derive_more = "0.99"
clap = { version = "4.0", features = ['cargo']}
serde = {version = "1.0", features = ['derive']}
reqwest = { version = "0.11", features = ["blocking"]}